### ISSUE TITLE
Implement LBNL workflow using RGD client

### ISSUE THREAD

**Issue by aashish24** [ResonantGeoData/RGD-ScrumBoard#19]

**Comment by banesullivan** [comment]
The data ingestion is done with the management command here: https://github.com/ResonantGeoData/RD-OASIS/blob/main/rdoasis/core/management/commands/oasis_dem.py

The AOI extraction code is implemented in RGD from previous efforts

We can now do the resampling with https://github.com/ResonantGeoData/ResonantGeoData/pull/457. Further, the Python client was updated here to implement the workflow. Once I wrap this up, I will publish the notebooks

**Comment by banesullivan** [comment]
Marking this epic is generally complete. There is still an outstanding issue which is outlined for the next sprint: https://github.com/ResonantGeoData/RD-OASIS/issues/10
