### ISSUE TITLE
Redesign Python Client

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/RGD-ScrumBoard#20]
After #17, we should redesign the Python client so that it is extensible and easy to interface with deployments that only have a subset of the RGD apps

FYI, getting tests going for the Python client is a high-priority item that I consider a requirement to start this. See https://github.com/ResonantGeoData/ResonantGeoData/issues/443

**Comment by banesullivan** [comment]
@AlmightyYakob, would you please post your thoughts and lessons learned from Girder-3 on how we could do this?

**Comment by jjnesbitt** [comment]
> @AlmightyYakob, would you please post your thoughts and lessons learned from Girder-3 on how we could do this?

At a high level, my thought was to make use of Python [Entry Points](https://setuptools.readthedocs.io/en/latest/userguide/entry_point.html#advertising-behavior). Girder3 makes use of this by using [`iter_entry_points`](https://setuptools.readthedocs.io/en/latest/pkg_resources.html#basic-workingset-methods), which may not be the current standard approach based on that first link. I need to look into it more.

If we structured the client this way, then the base RGD client would have the common features, and would expose an entry point that any plugin could hook into. This could also include the existing sub applications (`django-rgd-3d`, `django-rgd-fmv`, etc.).

Given that we use entry points, the second question is how do we want to structure plugins to make use of these entry points. One idea is to define a class that inherits from the base `Rgdc` class, and extends it to include any extra methods it needs ([example](https://github.com/girder/girder/blob/d55b2c60c678f7acc12f5c54b9d60f3838fcbab6/plugins/jobs/girder_jobs/__init__.py#L32-L39)). This may become complicated when making use of more than one plugin, more thought needs to go into the matter.

@banesullivan any thoughts on this?
