### ISSUE TITLE
RGD Logo

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/RGD-ScrumBoard#24]
Now that RGD is being deployed for various projects and we can consider it a broader framework for re-use in other Girder-4/Django projects, we should create a logo for branding and consistency.

This logo should be placed on:
- the main GitHub organization page
- The navbar of RGD's base template
- The favicon of RGD projects

Note that we had internal discussions about a logo back in January-ish here: https://kwgitlab.kitware.com/ux-design/design-tracker/-/issues/81

@aashish24, do you think we should push on the logo again?

**Comment by aashish24** [comment]
logo for RGD would be great. We can put it as priority for July sprint - specially as we are thinking of writing blogs and doing presentations, it will be helpful to have a logo.

**Comment by banesullivan** [comment]
Posted internally: https://kwgitlab.kitware.com/ux-design/design-tracker/-/issues/98

**Comment by aashish24** [comment]
@banesullivan did we get update logo design for consideration from @jtomeck ?

**Comment by banesullivan** [comment]
The design team is still working on this and they hope to have another iteration soon
