### ISSUE TITLE
Re-enable model upload and run using latest RGD

### ISSUE THREAD

**Issue by aashish24** [ResonantGeoData/RGD-ScrumBoard#26]

**Comment by banesullivan** [comment]
The "algorithms" app is mostly recovered in https://github.com/ResonantGeoData/RD-OASIS

I have a few open issues in the RD-OASIS repo for finishing this task though:

- https://github.com/ResonantGeoData/RD-OASIS/issues/1
- https://github.com/ResonantGeoData/RD-OASIS/issues/2
- https://github.com/ResonantGeoData/RD-OASIS/issues/3

Following this, we will need to implement tests and produce a demo to showcase that everything is working which is captured by:

- https://github.com/ResonantGeoData/RD-OASIS/issues/7
- https://github.com/ResonantGeoData/RD-OASIS/issues/4

**Comment by aashish24** [comment]
Split this into smaller tasks and convert this into milestone

**Comment by banesullivan** [comment]
See https://github.com/ResonantGeoData/RD-OASIS/milestone/1
