### ISSUE TITLE
STAC compliant search API for RGD (STAC REST)

### ISSUE THREAD

**Issue by aashish24** [ResonantGeoData/RGD-ScrumBoard#4]

**Comment by mcovalt** [comment]
The [STAC API specification](https://github.com/radiantearth/stac-api-spec) consists of:
1. a [core specification](https://api.stacspec.org/v1.0.0-beta.2/core/) that defines navigating catalogs
2. an [item search specification](https://api.stacspec.org/v1.0.0-beta.2/item-search/) that extends the core specification with varying levels of complexity:
	* [simple filtering](https://api.stacspec.org/v1.0.0-beta.2/item-search/#operation/getItemSearch)
	* [full featured filtering](https://api.stacspec.org/v1.0.0-beta.2/item-search/#operation/postItemSearch)

The core specification can be implemented with a view defining the root document. Child links can point to a complete STAC ItemCollection of each collection visible to the user.

Our current filter has a superset of the facets defined in the STAC "simple filtering". The "simple filtering" specification can be implemented similarly to our current search filter.

Later, a [pagination class](https://www.django-rest-framework.org/api-guide/pagination) can be used to conform to the search pagination. [Filtering on other fields](https://github.com/radiantearth/stac-api-spec/tree/master/fragments/filter) requires either parsing CQL or [a simpler custom boolean query language](https://github.com/radiantearth/stac-api-spec/tree/master/fragments/query). In either case, this adds considerable complexity to reach feature parity with our current filter.
